twitter:
  oauthConsumerKey: "CMyzGTyHaurHEpPq2OcoVATnS"
  oauthConsumerSecret: "op1xztNinm2AWyDQh9Abr7LZGQF9RNssijuA2tzOX0vLnuzzhW"
  oAuthAccessToken: "2930080269-yoT21zl5f3HCoJpx7rZXGznP3wXaVLfdH1FrQET"
  oAuthAccessTokenSecret: "nDBAD3z6aP5qT4ajvZbcsL0IHzmcb3DAliGFgL7u0H9L5"
